<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="BackupZCrypt.Composition" />
    <InternalsVisibleTo Include="BackupZCrypt.Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackupZCrypt.Domain\BackupZCrypt.Domain.csproj" />
  </ItemGroup>

</Project>
