//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupZCrypt.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupZCrypt.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation stopped due to access denied error: {0}.
        /// </summary>
        public static string AccessDeniedStoppedFormat {
            get {
                return ResourceManager.GetString("AccessDeniedStoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to process any files. Errors: {0}.
        /// </summary>
        public static string AllFilesFailedFormat {
            get {
                return ResourceManager.GetString("AllFilesFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cipher error for file: {0} - {1}.
        /// </summary>
        public static string CipherErrorFormat {
            get {
                return ResourceManager.GetString("CipherErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please confirm your password..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corrupted file (skipped): {0} - {1}.
        /// </summary>
        public static string CorruptedFileSkippedFormat {
            get {
                return ResourceManager.GetString("CorruptedFileSkippedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied to destination path. Please check permissions or run as administrator..
        /// </summary>
        public static string DestinationAccessDenied {
            get {
                return ResourceManager.GetString("DestinationAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The destination drive &apos;{0}&apos; does not exist or is not accessible..
        /// </summary>
        public static string DestinationDriveNotAccessibleFormat {
            get {
                return ResourceManager.GetString("DestinationDriveNotAccessibleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination contains {0} existing file(s) that may be overwritten..
        /// </summary>
        public static string DestinationExistingFilesFormat {
            get {
                return ResourceManager.GetString("DestinationExistingFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination directory cannot be inside the source directory. This would create a recursive operation..
        /// </summary>
        public static string DestinationInsideSource {
            get {
                return ResourceManager.GetString("DestinationInsideSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid destination path: {0}.
        /// </summary>
        public static string DestinationInvalidFormat {
            get {
                return ResourceManager.GetString("DestinationInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a destination path..
        /// </summary>
        public static string DestinationPathEmpty {
            get {
                return ResourceManager.GetString("DestinationPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot write to destination path: {0}.
        /// </summary>
        public static string DestinationWriteErrorFormat {
            get {
                return ResourceManager.GetString("DestinationWriteErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty password. Please enter a password..
        /// </summary>
        public static string EmptyPasswordDescription {
            get {
                return ResourceManager.GetString("EmptyPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encryption error for file: {0} - {1}.
        /// </summary>
        public static string EncryptionErrorFormat {
            get {
                return ResourceManager.GetString("EncryptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entropy: {0} bits.
        /// </summary>
        public static string EntropyFormat {
            get {
                return ResourceManager.GetString("EntropyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File not found (skipped): {0} - {1}.
        /// </summary>
        public static string FileNotFoundSkippedFormat {
            get {
                return ResourceManager.GetString("FileNotFoundSkippedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good job!.
        /// </summary>
        public static string GoodJob {
            get {
                return ResourceManager.GetString("GoodJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation stopped due to insufficient disk space: {0}.
        /// </summary>
        public static string InsufficientSpaceStoppedFormat {
            get {
                return ResourceManager.GetString("InsufficientSpaceStoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation stopped due to invalid password: {0}.
        /// </summary>
        public static string InvalidPasswordStoppedFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordStoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid path: {0}.
        /// </summary>
        public static string InvalidPathFormat {
            get {
                return ResourceManager.GetString("InvalidPathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation stopped due to key derivation error: {0}.
        /// </summary>
        public static string KeyDerivationStoppedFormat {
            get {
                return ResourceManager.GetString("KeyDerivationStoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Large operation: {0} files will be processed. This may take considerable time..
        /// </summary>
        public static string LargeOperationFormat {
            get {
                return ResourceManager.GetString("LargeOperationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low disk space: Available {0}, estimated need {1}.
        /// </summary>
        public static string LowDiskSpaceFormat {
            get {
                return ResourceManager.GetString("LowDiskSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create encrypted manifest at &apos;{0}&apos;..
        /// </summary>
        public static string ManifestCreateFailedFormat {
            get {
                return ResourceManager.GetString("ManifestCreateFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manifest file ignored during decryption..
        /// </summary>
        public static string ManifestIgnored {
            get {
                return ResourceManager.GetString("ManifestIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to write or encrypt manifest: {0}.
        /// </summary>
        public static string ManifestWriteFailedFormat {
            get {
                return ResourceManager.GetString("ManifestWriteFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium operation: {0} files will be processed..
        /// </summary>
        public static string MediumOperationFormat {
            get {
                return ResourceManager.GetString("MediumOperationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No characters available for password generation with the given options.
        /// </summary>
        public static string NoCharactersAvailable {
            get {
                return ResourceManager.GetString("NoCharactersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No files found in the source directory..
        /// </summary>
        public static string NoFilesInSourceDirectory {
            get {
                return ResourceManager.GetString("NoFilesInSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password should not start or end with spaces..
        /// </summary>
        public static string PasswordLeadingTrailingSpaces {
            get {
                return ResourceManager.GetString("PasswordLeadingTrailingSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password length must be greater than 0.
        /// </summary>
        public static string PasswordLengthNonPositive {
            get {
                return ResourceManager.GetString("PasswordLengthNonPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password and confirmation password do not match. Please check both fields..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At least one character type must be selected.
        /// </summary>
        public static string PasswordOptionsNone {
            get {
                return ResourceManager.GetString("PasswordOptionsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a password for encryption/decryption..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too long (maximum 1000 characters)..
        /// </summary>
        public static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at least 8 characters long for security..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied to the source path. Please check permissions or run as administrator..
        /// </summary>
        public static string SourceAccessDenied {
            get {
                return ResourceManager.GetString("SourceAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error accessing source path: {0}.
        /// </summary>
        public static string SourceAccessErrorFormat {
            get {
                return ResourceManager.GetString("SourceAccessErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source and destination directories cannot be the same. Please choose a different destination..
        /// </summary>
        public static string SourceDestinationSameDirectory {
            get {
                return ResourceManager.GetString("SourceDestinationSameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source and destination files cannot be the same. Please choose a different destination..
        /// </summary>
        public static string SourceDestinationSameFile {
            get {
                return ResourceManager.GetString("SourceDestinationSameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected directory is empty - no files to process..
        /// </summary>
        public static string SourceDirectoryEmpty {
            get {
                return ResourceManager.GetString("SourceDirectoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected file is empty and cannot be processed..
        /// </summary>
        public static string SourceFileEmpty {
            get {
                return ResourceManager.GetString("SourceFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source directory cannot be inside the destination directory. Please choose a different path..
        /// </summary>
        public static string SourceInsideDestination {
            get {
                return ResourceManager.GetString("SourceInsideDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a source file or directory to process..
        /// </summary>
        public static string SourcePathEmpty {
            get {
                return ResourceManager.GetString("SourcePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source path does not exist..
        /// </summary>
        public static string SourcePathNotExist {
            get {
                return ResourceManager.GetString("SourcePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected source path does not exist: {0}.
        /// </summary>
        public static string SourcePathNotExistFormat {
            get {
                return ResourceManager.GetString("SourcePathNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fair.
        /// </summary>
        public static string StrengthFair {
            get {
                return ResourceManager.GetString("StrengthFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good.
        /// </summary>
        public static string StrengthGood {
            get {
                return ResourceManager.GetString("StrengthGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strong.
        /// </summary>
        public static string StrengthStrong {
            get {
                return ResourceManager.GetString("StrengthStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Very Weak.
        /// </summary>
        public static string StrengthVeryWeak {
            get {
                return ResourceManager.GetString("StrengthVeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weak.
        /// </summary>
        public static string StrengthWeak {
            get {
                return ResourceManager.GetString("StrengthWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suggestions:.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add digits.
        /// </summary>
        public static string TipAddDigits {
            get {
                return ResourceManager.GetString("TipAddDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add lowercase letters.
        /// </summary>
        public static string TipAddLowercase {
            get {
                return ResourceManager.GetString("TipAddLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add symbols.
        /// </summary>
        public static string TipAddSymbols {
            get {
                return ResourceManager.GetString("TipAddSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add uppercase letters.
        /// </summary>
        public static string TipAddUppercase {
            get {
                return ResourceManager.GetString("TipAddUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avoid sequences (e.g. abc, 123, qwerty).
        /// </summary>
        public static string TipAvoidSequences {
            get {
                return ResourceManager.GetString("TipAvoidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avoid years.
        /// </summary>
        public static string TipAvoidYears {
            get {
                return ResourceManager.GetString("TipAvoidYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increase length (≥12 chars).
        /// </summary>
        public static string TipIncreaseLength {
            get {
                return ResourceManager.GetString("TipIncreaseLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use more character variety.
        /// </summary>
        public static string TipMoreVariety {
            get {
                return ResourceManager.GetString("TipMoreVariety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reduce repeated characters.
        /// </summary>
        public static string TipReduceRepeats {
            get {
                return ResourceManager.GetString("TipReduceRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred: {0}.
        /// </summary>
        public static string UnexpectedErrorFormat {
            get {
                return ResourceManager.GetString("UnexpectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsupported operation: {0}.
        /// </summary>
        public static string UnsupportedOperationFormat {
            get {
                return ResourceManager.GetString("UnsupportedOperationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password strength is below recommended level. Consider using a stronger password..
        /// </summary>
        public static string WeakPasswordWarning {
            get {
                return ResourceManager.GetString("WeakPasswordWarning", resourceCulture);
            }
        }
    }
}
