//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudZCrypt.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudZCrypt.Infrastructure.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A NIST-standardized 128‑bit block cipher with a 256‑bit key, widely accelerated via AES-NI and ARMv8 Cryptography Extensions. Galois/Counter Mode (GCM) provides authenticated encryption with associated data (AEAD), combining high performance, confidentiality, and integrity..
        /// </summary>
        internal static string AesDescription {
            get {
                return ResourceManager.GetString("AesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AES-256 GCM.
        /// </summary>
        internal static string AesDisplayName {
            get {
                return ResourceManager.GetString("AesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for general purposes (with hardware acceleration).
        /// </summary>
        internal static string AesSummary {
            get {
                return ResourceManager.GetString("AesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A modern memory‑hard password hashing and key derivation function (PHC winner). The &quot;id&quot; variant blends Argon2i (side‑channel resistant) and Argon2d (GPU/ASIC resistance) for balanced security. Tunable via: memory cost (m), iterations/time cost (t), and parallelism (p). Provides strong resistance to large‑scale brute force on GPUs, FPGAs, and ASICs by imposing substantial RAM requirements. Supports domain separation with distinct salt plus optional secret/data parameters. Recommended where modern security i [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Argon2idDescription {
            get {
                return ResourceManager.GetString("Argon2idDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argon2id.
        /// </summary>
        internal static string Argon2idDisplayName {
            get {
                return ResourceManager.GetString("Argon2idDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deriving key with Argon2id.
        /// </summary>
        internal static string Argon2idKeyDerivationError {
            get {
                return ResourceManager.GetString("Argon2idKeyDerivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for maximum security / modern memory‑hard password hashing.
        /// </summary>
        internal static string Argon2idSummary {
            get {
                return ResourceManager.GetString("Argon2idSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A high-quality block-sorting compression algorithm that achieves better compression ratios than GZip at the cost of slower speed. Well suited for archiving scenarios where file size reduction is more important than throughput..
        /// </summary>
        internal static string BZip2Description {
            get {
                return ResourceManager.GetString("BZip2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BZip2.
        /// </summary>
        internal static string BZip2DisplayName {
            get {
                return ResourceManager.GetString("BZip2DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Higher compression ratio than GZip.
        /// </summary>
        internal static string BZip2Summary {
            get {
                return ResourceManager.GetString("BZip2Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A 128‑bit block cipher with a 256‑bit key, jointly designed by NTT and Mitsubishi; performance and security margin comparable to AES. Supported in many international standards (RFCs, ISO/IEC) and suitable where non‑U.S.-origin algorithms or broader jurisdictional acceptance is desired. Used with GCM for AEAD..
        /// </summary>
        internal static string CamelliaDescription {
            get {
                return ResourceManager.GetString("CamelliaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camellia-256 GCM.
        /// </summary>
        internal static string CamelliaDisplayName {
            get {
                return ResourceManager.GetString("CamelliaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for international compliance.
        /// </summary>
        internal static string CamelliaSummary {
            get {
                return ResourceManager.GetString("CamelliaSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A modern ARX (Add-Rotate-XOR) stream cipher (ChaCha20) combined with the Poly1305 MAC to form a fast, timing‑attack‑resistant AEAD construction that performs especially well on devices lacking AES hardware acceleration. Standardized in RFC 8439 and widely deployed in TLS, SSH, QUIC, and WireGuard..
        /// </summary>
        internal static string ChaCha20Description {
            get {
                return ResourceManager.GetString("ChaCha20Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ChaCha20-Poly1305.
        /// </summary>
        internal static string ChaCha20DisplayName {
            get {
                return ResourceManager.GetString("ChaCha20DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for general purposes (without hardware acceleration).
        /// </summary>
        internal static string ChaCha20Summary {
            get {
                return ResourceManager.GetString("ChaCha20Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replaces the filename with a randomly generated GUID. Provides strong privacy by producing non-predictable, non-correlatable names for each file..
        /// </summary>
        internal static string GuidDescription {
            get {
                return ResourceManager.GetString("GuidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUID.
        /// </summary>
        internal static string GuidDisplayName {
            get {
                return ResourceManager.GetString("GuidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for maximum privacy (random).
        /// </summary>
        internal static string GuidSummary {
            get {
                return ResourceManager.GetString("GuidSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A widely supported compression algorithm (RFC 1952) based on the DEFLATE algorithm. Offers a good balance between compression ratio and speed, and is universally supported across operating systems, tools, and programming languages..
        /// </summary>
        internal static string GZipDescription {
            get {
                return ResourceManager.GetString("GZipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GZip.
        /// </summary>
        internal static string GZipDisplayName {
            get {
                return ResourceManager.GetString("GZipDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good balance, universal compatibility.
        /// </summary>
        internal static string GZipSummary {
            get {
                return ResourceManager.GetString("GZipSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Lempel-Ziv-Markov chain Algorithm used by 7-Zip, delivering one of the highest compression ratios among general-purpose compressors. Ideal for archiving and scenarios where minimizing file size is more important than compression speed..
        /// </summary>
        internal static string LzmaDescription {
            get {
                return ResourceManager.GetString("LzmaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LZMA (7-Zip).
        /// </summary>
        internal static string LzmaDisplayName {
            get {
                return ResourceManager.GetString("LzmaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highest compression ratio (slowest).
        /// </summary>
        internal static string LzmaSummary {
            get {
                return ResourceManager.GetString("LzmaSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No compression is applied. Files are encrypted as-is without any size reduction. Best when speed is critical or files are already compressed (e.g., ZIP, JPEG, MP4)..
        /// </summary>
        internal static string NoCompressionDescription {
            get {
                return ResourceManager.GetString("NoCompressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        internal static string NoCompressionDisplayName {
            get {
                return ResourceManager.GetString("NoCompressionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No compression (fastest).
        /// </summary>
        internal static string NoCompressionSummary {
            get {
                return ResourceManager.GetString("NoCompressionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preserves the original filename unchanged. Use when filename privacy is not required and human-readable organization should be retained..
        /// </summary>
        internal static string NoObfuscationDescription {
            get {
                return ResourceManager.GetString("NoObfuscationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        internal static string NoObfuscationDisplayName {
            get {
                return ResourceManager.GetString("NoObfuscationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best if filename obfuscation is not needed.
        /// </summary>
        internal static string NoObfuscationSummary {
            get {
                return ResourceManager.GetString("NoObfuscationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a decryption.
        /// </summary>
        internal static string OperationDecryption {
            get {
                return ResourceManager.GetString("OperationDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encryption.
        /// </summary>
        internal static string OperationEncryption {
            get {
                return ResourceManager.GetString("OperationEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A widely standardized (PKCS #5, RFC 8018, FIPS 140 allowed) iterative, CPU‑bound key derivation function using repeated HMAC-SHA256 applications. Simple and broadly implemented in virtually all cryptographic libraries. Lacks intrinsic memory hardness, making it comparatively cheaper to accelerate on GPUs/ASICs versus Argon2id or scrypt. Still appropriate where regulatory, legacy platform, or FIPS compliance requirements dominate, or when only conservative primitives are permitted. Security hinges on high it [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Pbkdf2Description {
            get {
                return ResourceManager.GetString("Pbkdf2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PBKDF2 (HMAC-SHA256).
        /// </summary>
        internal static string Pbkdf2DisplayName {
            get {
                return ResourceManager.GetString("Pbkdf2DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deriving key with PBKDF2.
        /// </summary>
        internal static string Pbkdf2KeyDerivationError {
            get {
                return ResourceManager.GetString("Pbkdf2KeyDerivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for maximum compatibility / legacy &amp; compliance needs.
        /// </summary>
        internal static string Pbkdf2Summary {
            get {
                return ResourceManager.GetString("Pbkdf2Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A memory‑hard key derivation function (RFC 7914) that requires large amounts of RAM to compute, making brute‑force attacks on GPUs, FPGAs, and ASICs significantly more expensive than CPU‑only functions like PBKDF2. Tunable via: CPU/memory cost parameter (N), block‑size factor (r), and parallelization parameter (p). Offers stronger hardware‑attack resistance than PBKDF2 and broader ecosystem support than Argon2id, being widely deployed in disk encryption (e.g., tarsnap), cryptocurrency systems, and password  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ScryptDescription {
            get {
                return ResourceManager.GetString("ScryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrypt.
        /// </summary>
        internal static string ScryptDisplayName {
            get {
                return ResourceManager.GetString("ScryptDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deriving key with scrypt.
        /// </summary>
        internal static string ScryptKeyDerivationError {
            get {
                return ResourceManager.GetString("ScryptKeyDerivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for memory‑hard security with broad ecosystem compatibility.
        /// </summary>
        internal static string ScryptSummary {
            get {
                return ResourceManager.GetString("ScryptSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A conservative 128‑bit block cipher finalist from the AES competition, designed with a large security margin and a 256‑bit key option. Typically slower than AES and Camellia. When wrapped in GCM it provides AEAD, but performance costs make it niche for high-assurance or defense-in-depth scenarios..
        /// </summary>
        internal static string SerpentDescription {
            get {
                return ResourceManager.GetString("SerpentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serpent-256 GCM.
        /// </summary>
        internal static string SerpentDisplayName {
            get {
                return ResourceManager.GetString("SerpentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for high-security purposes (slow).
        /// </summary>
        internal static string SerpentSummary {
            get {
                return ResourceManager.GetString("SerpentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replaces the filename with a 64‑character SHA‑256 hexadecimal digest computed from the file content. Deterministic across identical content, enabling deduplication and content-addressable naming without leaking the original filename..
        /// </summary>
        internal static string Sha256Description {
            get {
                return ResourceManager.GetString("Sha256Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHA-256.
        /// </summary>
        internal static string Sha256DisplayName {
            get {
                return ResourceManager.GetString("Sha256DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for content-addressed naming (64-char digest).
        /// </summary>
        internal static string Sha256Summary {
            get {
                return ResourceManager.GetString("Sha256Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replaces the filename with a 128‑character SHA‑512 hexadecimal digest computed from the file content. Offers stronger collision resistance than SHA‑256 at the cost of longer names; deterministic across identical content..
        /// </summary>
        internal static string Sha512Description {
            get {
                return ResourceManager.GetString("Sha512Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHA-512.
        /// </summary>
        internal static string Sha512DisplayName {
            get {
                return ResourceManager.GetString("Sha512DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for maximum collision resistance (128-char digest).
        /// </summary>
        internal static string Sha512Summary {
            get {
                return ResourceManager.GetString("Sha512Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A flexible 128‑bit block cipher (up to 256‑bit keys), also an AES finalist. Offers solid cryptanalytic resilience with a different design philosophy (Feistel + key-dependent S‑boxes) for algorithmic diversity. Less commonly hardware-accelerated or standardized for AEAD modes..
        /// </summary>
        internal static string TwofishDescription {
            get {
                return ResourceManager.GetString("TwofishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twofish-256 GCM.
        /// </summary>
        internal static string TwofishDisplayName {
            get {
                return ResourceManager.GetString("TwofishDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best for design diversity.
        /// </summary>
        internal static string TwofishSummary {
            get {
                return ResourceManager.GetString("TwofishSummary", resourceCulture);
            }
        }
    }
}
