<Project>

  <PropertyGroup>
    <Version>1.1.2</Version>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">

    <AnalysisLevel>10-recommended</AnalysisLevel>
    <AnalysisLevelSecurity>10-all</AnalysisLevelSecurity>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RunAnalyzers>true</RunAnalyzers>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <OptimizeImplicitlyTriggeredBuild>false</OptimizeImplicitlyTriggeredBuild>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>

  </PropertyGroup>

</Project>
