//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupZCrypt.Terminal.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupZCrypt.Terminal.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algorithm Information.
        /// </summary>
        internal static string AlgorithmInformation {
            get {
                return ResourceManager.GetString("AlgorithmInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A simple military-grade file encryption tool.
        /// </summary>
        internal static string BannerSubtitle {
            get {
                return ResourceManager.GetString("BannerSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelling….
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a characters.
        /// </summary>
        internal static string CharactersLabel {
            get {
                return ResourceManager.GetString("CharactersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completed successfully.
        /// </summary>
        internal static string CompletedSuccessfully {
            get {
                return ResourceManager.GetString("CompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compression.
        /// </summary>
        internal static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compression mode:.
        /// </summary>
        internal static string CompressionModePrompt {
            get {
                return ResourceManager.GetString("CompressionModePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compression Modes.
        /// </summary>
        internal static string CompressionModes {
            get {
                return ResourceManager.GetString("CompressionModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        internal static string ConfirmPasswordPrompt {
            get {
                return ResourceManager.GetString("ConfirmPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue with {0} despite warnings?.
        /// </summary>
        internal static string ContinueDespiteWarningsFormat {
            get {
                return ResourceManager.GetString("ContinueDespiteWarningsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrypt.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrypting.
        /// </summary>
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination path.
        /// </summary>
        internal static string DestinationPathPrompt {
            get {
                return ResourceManager.GetString("DestinationPathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elapsed time.
        /// </summary>
        internal static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encrypt.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encrypting.
        /// </summary>
        internal static string Encrypting {
            get {
                return ResourceManager.GetString("Encrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encryption algorithm:.
        /// </summary>
        internal static string EncryptionAlgorithmPrompt {
            get {
                return ResourceManager.GetString("EncryptionAlgorithmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encryption Algorithms.
        /// </summary>
        internal static string EncryptionAlgorithms {
            get {
                return ResourceManager.GetString("EncryptionAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encryption.
        /// </summary>
        internal static string EncryptionLabel {
            get {
                return ResourceManager.GetString("EncryptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errors:.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed files.
        /// </summary>
        internal static string FailedFiles {
            get {
                return ResourceManager.GetString("FailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ❌ {0} failed: {1}.
        /// </summary>
        internal static string FailedFormat {
            get {
                return ResourceManager.GetString("FailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files processed.
        /// </summary>
        internal static string FilesProcessed {
            get {
                return ResourceManager.GetString("FilesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔐 Generated Password.
        /// </summary>
        internal static string GeneratedPasswordHeader {
            get {
                return ResourceManager.GetString("GeneratedPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goodbye!.
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Include:.
        /// </summary>
        internal static string IncludePrompt {
            get {
                return ResourceManager.GetString("IncludePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key derivation algorithm:.
        /// </summary>
        internal static string KeyDerivationAlgorithmPrompt {
            get {
                return ResourceManager.GetString("KeyDerivationAlgorithmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key Derivation Algorithms.
        /// </summary>
        internal static string KeyDerivationAlgorithms {
            get {
                return ResourceManager.GetString("KeyDerivationAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key Derivation.
        /// </summary>
        internal static string KeyDerivationLabel {
            get {
                return ResourceManager.GetString("KeyDerivationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length:.
        /// </summary>
        internal static string LengthLabel {
            get {
                return ResourceManager.GetString("LengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ℹ️ Algorithm Info.
        /// </summary>
        internal static string MenuAlgorithmInfo {
            get {
                return ResourceManager.GetString("MenuAlgorithmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔓 Decrypt.
        /// </summary>
        internal static string MenuDecrypt {
            get {
                return ResourceManager.GetString("MenuDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔒 Encrypt.
        /// </summary>
        internal static string MenuEncrypt {
            get {
                return ResourceManager.GetString("MenuEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ❌ Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🔑 Generate Password.
        /// </summary>
        internal static string MenuGeneratePassword {
            get {
                return ResourceManager.GetString("MenuGeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metric.
        /// </summary>
        internal static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name Obfuscation.
        /// </summary>
        internal static string NameObfuscationLabel {
            get {
                return ResourceManager.GetString("NameObfuscationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name obfuscation mode:.
        /// </summary>
        internal static string NameObfuscationModePrompt {
            get {
                return ResourceManager.GetString("NameObfuscationModePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name Obfuscation Modes.
        /// </summary>
        internal static string NameObfuscationModes {
            get {
                return ResourceManager.GetString("NameObfuscationModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation cancelled..
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation cancelled by user..
        /// </summary>
        internal static string OperationCancelledByUser {
            get {
                return ResourceManager.GetString("OperationCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1}/{2} files.
        /// </summary>
        internal static string OperationIngFilesFormat {
            get {
                return ResourceManager.GetString("OperationIngFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}….
        /// </summary>
        internal static string OperationIngFormat {
            get {
                return ResourceManager.GetString("OperationIngFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lowercase (a-z).
        /// </summary>
        internal static string OptionLowercase {
            get {
                return ResourceManager.GetString("OptionLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numbers (0-9).
        /// </summary>
        internal static string OptionNumbers {
            get {
                return ResourceManager.GetString("OptionNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special characters (!@#$).
        /// </summary>
        internal static string OptionSpecialChars {
            get {
                return ResourceManager.GetString("OptionSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uppercase (A-Z).
        /// </summary>
        internal static string OptionUppercase {
            get {
                return ResourceManager.GetString("OptionUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partially completed.
        /// </summary>
        internal static string PartiallyCompleted {
            get {
                return ResourceManager.GetString("PartiallyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password cannot be empty.
        /// </summary>
        internal static string PasswordCannotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password Generator.
        /// </summary>
        internal static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length must be between 16 and 256.
        /// </summary>
        internal static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password length.
        /// </summary>
        internal static string PasswordLengthPrompt {
            get {
                return ResourceManager.GetString("PasswordLengthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (16–256):.
        /// </summary>
        internal static string PasswordLengthRange {
            get {
                return ResourceManager.GetString("PasswordLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Store this password securely — it cannot be recovered if lost!.
        /// </summary>
        internal static string PasswordStorageWarning {
            get {
                return ResourceManager.GetString("PasswordStorageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password strength:.
        /// </summary>
        internal static string PasswordStrengthLabel {
            get {
                return ResourceManager.GetString("PasswordStrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path cannot be empty.
        /// </summary>
        internal static string PathCannotBeEmpty {
            get {
                return ResourceManager.GetString("PathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path does not exist.
        /// </summary>
        internal static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a destination path.
        /// </summary>
        internal static string PleaseEnterDestinationPath {
            get {
                return ResourceManager.GetString("PleaseEnterDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press any key to return to the menu….
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceed with {0}?.
        /// </summary>
        internal static string ProceedConfirmFormat {
            get {
                return ResourceManager.GetString("ProceedConfirmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (file or directory):.
        /// </summary>
        internal static string SourcePathHint {
            get {
                return ResourceManager.GetString("SourcePathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source path.
        /// </summary>
        internal static string SourcePathPrompt {
            get {
                return ResourceManager.GetString("SourcePathPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strength:.
        /// </summary>
        internal static string StrengthLabel {
            get {
                return ResourceManager.GetString("StrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary.
        /// </summary>
        internal static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Throughput.
        /// </summary>
        internal static string Throughput {
            get {
                return ResourceManager.GetString("Throughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Press &lt;space&gt; to toggle, &lt;enter&gt; to confirm).
        /// </summary>
        internal static string ToggleInstructions {
            get {
                return ResourceManager.GetString("ToggleInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total size.
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ❌ Unexpected error: {0}.
        /// </summary>
        internal static string UnexpectedErrorFormat {
            get {
                return ResourceManager.GetString("UnexpectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ❌ Validation error: {0}.
        /// </summary>
        internal static string ValidationErrorFormat {
            get {
                return ResourceManager.GetString("ValidationErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation errors:.
        /// </summary>
        internal static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warnings:.
        /// </summary>
        internal static string WarningsLabel {
            get {
                return ResourceManager.GetString("WarningsLabel", resourceCulture);
            }
        }
    }
}
