//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupZCrypt.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupZCrypt.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied to file: {0}.
        /// </summary>
        public static string AccessDeniedFormat {
            get {
                return ResourceManager.GetString("AccessDeniedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot access value of failed result.
        /// </summary>
        public static string CannotAccessFailedResultValue {
            get {
                return ResourceManager.GetString("CannotAccessFailedResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cipher operation failed during {0}.
        /// </summary>
        public static string CipherOperationFailedFormat {
            get {
                return ResourceManager.GetString("CipherOperationFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compression mode &apos;{0}&apos; is not registered..
        /// </summary>
        public static string CompressionModeNotRegisteredFormat {
            get {
                return ResourceManager.GetString("CompressionModeNotRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The encrypted file appears to be corrupted or invalid: {0}.
        /// </summary>
        public static string CorruptedFileFormat {
            get {
                return ResourceManager.GetString("CorruptedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encryption algorithm &apos;{0}&apos; is not registered..
        /// </summary>
        public static string EncryptionAlgorithmNotRegisteredFormat {
            get {
                return ResourceManager.GetString("EncryptionAlgorithmNotRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File not found: {0}.
        /// </summary>
        public static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insufficient disk space at: {0}.
        /// </summary>
        public static string InsufficientDiskSpaceFormat {
            get {
                return ResourceManager.GetString("InsufficientDiskSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid password or corrupted file. Please verify the password and file integrity..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key derivation algorithm &apos;{0}&apos; is not registered..
        /// </summary>
        public static string KeyDerivationAlgorithmNotRegisteredFormat {
            get {
                return ResourceManager.GetString("KeyDerivationAlgorithmNotRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to derive encryption key from password.
        /// </summary>
        public static string KeyDerivationFailed {
            get {
                return ResourceManager.GetString("KeyDerivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name obfuscation mode &apos;{0}&apos; is not registered..
        /// </summary>
        public static string NameObfuscationModeNotRegisteredFormat {
            get {
                return ResourceManager.GetString("NameObfuscationModeNotRegisteredFormat", resourceCulture);
            }
        }
    }
}
