using System.Diagnostics;
using BackupZCrypt.Application.Orchestrators.Interfaces;
using BackupZCrypt.Application.Services.Interfaces;
using BackupZCrypt.Application.ValueObjects.Backup;
using BackupZCrypt.Application.ValueObjects.Manifest;
using BackupZCrypt.Domain.Constants;
using BackupZCrypt.Domain.Enums;
using BackupZCrypt.Domain.Strategies.Interfaces;
using BackupZCrypt.Domain.ValueObjects.Backup;
using BackupZCrypt.Terminal.Rendering;
using BackupZCrypt.Terminal.Resources;
using BackupZCrypt.Terminal.Services.Interfaces;
using Spectre.Console;

namespace BackupZCrypt.Terminal.Commands;

internal sealed class BackupCommand(
    IBackupOrchestrator orchestrator,
    ISettingsService settingsService,
    IPasswordService passwordService,
    IManifestService manifestService,
    IPathPromptService pathPromptService,
    IReadOnlyList<IEncryptionAlgorithmStrategy> encryptionStrategies,
    IReadOnlyList<IKeyDerivationAlgorithmStrategy> keyDerivationStrategies,
    IReadOnlyList<ICompressionStrategy> compressionStrategies
)
{
    public async Task ExecuteAsync(BackupOperation operation)
    {
        var operationName = operation switch
        {
            BackupOperation.Create => Messages.CreateBackup,
            BackupOperation.Update => Messages.UpdateBackup,
            _ => Messages.RestoreBackup,
        };

        AnsiConsole.Write(
            new Rule($"[bold cyan]{operationName}[/]").RuleStyle(Style.Parse("grey"))
        );
        AnsiConsole.WriteLine();

        if (operation == BackupOperation.Update)
        {
            await ExecuteUpdateBackupAsync(operationName);
            return;
        }

        var sourcePath = await pathPromptService.PromptSourcePathAsync();
        var destinationPath = await pathPromptService.PromptDestinationPathAsync();

        if (operation == BackupOperation.Create)
        {
            await ExecuteCreateBackupAsync(operationName, sourcePath, destinationPath);
        }
        else
        {
            await ExecuteRestoreBackupAsync(operationName, sourcePath, destinationPath);
        }
    }

    private async Task ExecuteCreateBackupAsync(
        string operationName,
        string sourcePath,
        string destinationPath
    )
    {
        BackupCreationSettings settings;

        try
        {
            settings = await settingsService.GetOrCreateAsync<BackupCreationSettings>();
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.UnexpectedErrorFormat, Markup.Escape(ex.Message))}[/]"
            );
            return;
        }

        var selectedEncryption = this.ResolveEncryptionStrategy(settings);

        var password = string.Empty;
        var confirmPassword = string.Empty;
        var selectedKdf = this.ResolveKeyDerivationStrategy(settings);
        if (selectedEncryption is not null)
        {
            bool wasAutoGenerated;
            (password, confirmPassword, wasAutoGenerated) = PromptPasswords();

            if (wasAutoGenerated)
            {
                PrintGeneratedPassword(password);
            }
        }

        var selectedCompression = this.ResolveCompressionStrategy(settings);

        PrintSummary(
            operationName,
            sourcePath,
            destinationPath,
            selectedEncryption,
            selectedKdf,
            selectedCompression
        );

        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ProceedConfirmFormat, operationName.ToUpperInvariant())}[/]"
            )
        )
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return;
        }

        await pathPromptService.RememberPathsAsync(sourcePath, destinationPath);

        if (selectedEncryption is not null)
        {
            BackupRequest request = new(
                sourcePath,
                destinationPath,
                password,
                confirmPassword,
                selectedEncryption.Id,
                selectedKdf!.Id,
                BackupOperation.Create,
                selectedCompression?.Id ?? CompressionMode.None,
                ProceedOnWarnings: false
            );

            await RunOperationAsync(request, operationName, Messages.Encrypting);
        }
        else if (selectedCompression is not null)
        {
            BackupRequest request = new(
                sourcePath,
                destinationPath,
                string.Empty,
                string.Empty,
                default,
                default,
                BackupOperation.Create,
                selectedCompression.Id,
                ProceedOnWarnings: false
            );

            await RunOperationAsync(request, operationName, Messages.Compressing);
        }
        else
        {
            await ExecutePlainCopyAsync(operationName, sourcePath, destinationPath);
        }
    }

    private async Task ExecuteRestoreBackupAsync(
        string operationName,
        string sourcePath,
        string destinationPath
    )
    {
        var manifestKind = DetectManifestKind(sourcePath);

        if (manifestKind == ManifestKind.Missing)
        {
            AnsiConsole.MarkupLine($"[red]{Messages.ManifestNotFound}[/]");
            return;
        }

        var password = string.Empty;
        if (manifestKind == ManifestKind.Encrypted)
        {
            AnsiConsole.MarkupLine($"[cyan]{Messages.EncryptedBackupDetected}[/]");
            password = PromptDecryptionPassword();
        }
        else
        {
            AnsiConsole.MarkupLine($"[dim]{Messages.NoEncryptionDetected}[/]");
        }

        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ProceedConfirmFormat, operationName.ToUpperInvariant())}[/]"
            )
        )
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return;
        }

        await pathPromptService.RememberPathsAsync(sourcePath, destinationPath);

        if (manifestKind == ManifestKind.PlainCopy)
        {
            await ExecutePlainRestoreAsync(operationName, sourcePath, destinationPath);
            return;
        }

        BackupRequest request = new(
            sourcePath,
            destinationPath,
            password,
            password,
            manifestKind == ManifestKind.Encrypted
                ? EncryptionAlgorithm.Aes
                : EncryptionAlgorithm.None,
            KeyDerivationAlgorithm.Argon2id,
            BackupOperation.Restore
        );

        await RunOperationAsync(
            request,
            operationName,
            manifestKind == ManifestKind.Encrypted ? Messages.Decrypting : Messages.Decompressing
        );
    }

    private async Task ExecuteUpdateBackupAsync(string operationName)
    {
        var sourcePath = await pathPromptService.PromptUpdateSourcePathAsync();
        var backupPath = await pathPromptService.PromptUpdateBackupPathAsync();

        var manifestKind = DetectManifestKind(backupPath);

        if (manifestKind == ManifestKind.Missing)
        {
            AnsiConsole.MarkupLine($"[red]{Messages.UpdateManifestNotFound}[/]");
            return;
        }

        var password = string.Empty;
        if (manifestKind == ManifestKind.Encrypted)
        {
            AnsiConsole.MarkupLine($"[cyan]{Messages.EncryptedBackupDetected}[/]");
            password = PromptDecryptionPassword();
        }
        else
        {
            AnsiConsole.MarkupLine($"[dim]{Messages.NoEncryptionDetected}[/]");
        }

        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ProceedConfirmFormat, operationName.ToUpperInvariant())}[/]"
            )
        )
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return;
        }

        await pathPromptService.RememberPathsAsync(sourcePath, backupPath);

        BackupRequest request = new(
            sourcePath,
            backupPath,
            password,
            password,
            manifestKind == ManifestKind.Encrypted
                ? EncryptionAlgorithm.Aes
                : EncryptionAlgorithm.None,
            KeyDerivationAlgorithm.Argon2id,
            BackupOperation.Update
        );

        await RunOperationAsync(request, operationName, Messages.Updating);
    }

    private async Task ExecutePlainCopyAsync(
        string operationName,
        string sourcePath,
        string destinationPath
    )
    {
        AnsiConsole.WriteLine();

        using CancellationTokenSource cts = new();

        ConsoleCancelEventHandler cancelHandler = (_, e) =>
        {
            e.Cancel = true;
            cts.Cancel();
            AnsiConsole.MarkupLine($"[yellow]{Messages.Cancelling}[/]");
        };

        Console.CancelKeyPress += cancelHandler;

        try
        {
            var sw = Stopwatch.StartNew();
            List<string> errors = [];
            var processedFiles = 0;
            long totalBytes = 0;
            int totalFileCount;

            if (Directory.Exists(sourcePath))
            {
                if (Directory.Exists(destinationPath))
                {
                    Directory.Delete(destinationPath, recursive: true);
                    Directory.CreateDirectory(destinationPath);
                }

                var files = Directory.GetFiles(sourcePath, "*", SearchOption.AllDirectories);
                totalFileCount = files.Length;

                await AnsiConsole
                    .Progress()
                    .AutoClear(false)
                    .HideCompleted(false)
                    .Columns(
                        new TaskDescriptionColumn(),
                        new ProgressBarColumn(),
                        new PercentageColumn(),
                        new RemainingTimeColumn(),
                        new SpinnerColumn()
                    )
                    .StartAsync(async ctx =>
                    {
                        var task = ctx.AddTask(
                            $"[cyan]{string.Format(Messages.OperationIngFormat, Messages.Copying)}[/]",
                            maxValue: Math.Max(totalFileCount, 1)
                        );

                        foreach (var file in files)
                        {
                            cts.Token.ThrowIfCancellationRequested();

                            var relativePath = Path.GetRelativePath(sourcePath, file);
                            var destFile = Path.Combine(destinationPath, relativePath);
                            var destDir = Path.GetDirectoryName(destFile);

                            if (destDir is not null)
                            {
                                Directory.CreateDirectory(destDir);
                            }

                            try
                            {
                                await using FileStream sourceStream = new(
                                    file,
                                    FileMode.Open,
                                    FileAccess.Read,
                                    FileShare.Read,
                                    4096,
                                    useAsync: true
                                );
                                await using FileStream destStream = new(
                                    destFile,
                                    FileMode.Create,
                                    FileAccess.Write,
                                    FileShare.None,
                                    4096,
                                    useAsync: true
                                );
                                await sourceStream.CopyToAsync(destStream, cts.Token);

                                totalBytes += new FileInfo(file).Length;
                                processedFiles++;
                            }
                            catch (Exception ex) when (ex is not OperationCanceledException)
                            {
                                errors.Add($"{relativePath}: {ex.Message}");
                            }

                            task.Value = processedFiles + errors.Count;
                            task.Description =
                                $"[cyan]{string.Format(Messages.OperationIngFilesFormat, Messages.Copying, processedFiles, totalFileCount)}[/]";
                        }
                    });
            }
            else
            {
                totalFileCount = 1;

                await AnsiConsole
                    .Progress()
                    .AutoClear(false)
                    .HideCompleted(false)
                    .Columns(
                        new TaskDescriptionColumn(),
                        new ProgressBarColumn(),
                        new PercentageColumn(),
                        new SpinnerColumn()
                    )
                    .StartAsync(async ctx =>
                    {
                        var task = ctx.AddTask(
                            $"[cyan]{string.Format(Messages.OperationIngFormat, Messages.Copying)}[/]",
                            maxValue: 1
                        );

                        string destFile;

                        if (Directory.Exists(destinationPath))
                        {
                            destFile = Path.Combine(destinationPath, Path.GetFileName(sourcePath));
                        }
                        else
                        {
                            var destDir = Path.GetDirectoryName(destinationPath);

                            if (destDir is not null)
                            {
                                Directory.CreateDirectory(destDir);
                            }

                            destFile = destinationPath;
                        }

                        try
                        {
                            await using FileStream sourceStream = new(
                                sourcePath,
                                FileMode.Open,
                                FileAccess.Read,
                                FileShare.Read,
                                4096,
                                useAsync: true
                            );
                            await using FileStream destStream = new(
                                destFile,
                                FileMode.Create,
                                FileAccess.Write,
                                FileShare.None,
                                4096,
                                useAsync: true
                            );
                            await sourceStream.CopyToAsync(destStream, cts.Token);

                            totalBytes = new FileInfo(sourcePath).Length;
                            processedFiles = 1;
                        }
                        catch (Exception ex) when (ex is not OperationCanceledException)
                        {
                            errors.Add(ex.Message);
                        }

                        task.Value = 1;
                    });
            }

            sw.Stop();

            if (errors.Count == 0 && processedFiles > 0)
            {
                List<ManifestEntry> entries = [];
                string manifestDir;

                if (Directory.Exists(sourcePath))
                {
                    manifestDir = destinationPath;
                    var files = Directory.GetFiles(
                        destinationPath,
                        "*",
                        SearchOption.AllDirectories
                    );

                    foreach (var file in files)
                    {
                        var relativePath = Path.GetRelativePath(destinationPath, file);
                        entries.Add(
                            new ManifestEntry(
                                relativePath,
                                relativePath,
                                string.Empty,
                                string.Empty,
                                string.Empty
                            )
                        );
                    }
                }
                else
                {
                    var destFile = Directory.Exists(destinationPath)
                        ? Path.Combine(destinationPath, Path.GetFileName(sourcePath))
                        : destinationPath;
                    manifestDir = Path.GetDirectoryName(destFile) ?? destinationPath;
                    var fileName = Path.GetFileName(destFile);
                    entries.Add(
                        new ManifestEntry(
                            fileName,
                            fileName,
                            string.Empty,
                            string.Empty,
                            string.Empty
                        )
                    );
                }

                ManifestHeader header = new(default, default, CompressionMode.None);

                await manifestService.TrySavePlainManifestAsync(
                    entries,
                    header,
                    manifestDir,
                    cts.Token
                );
            }

            BackupResult result = new(
                errors.Count == 0,
                sw.Elapsed,
                totalBytes,
                processedFiles,
                totalFileCount,
                errors,
                []
            );

            ResultRenderer.Print(result, operationName);
        }
        catch (OperationCanceledException)
        {
            AnsiConsole.MarkupLine($"[yellow]{Messages.OperationCancelledByUser}[/]");
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.UnexpectedErrorFormat, Markup.Escape(ex.Message))}[/]"
            );
        }
        finally
        {
            Console.CancelKeyPress -= cancelHandler;
        }
    }

    private static async Task ExecutePlainRestoreAsync(
        string operationName,
        string sourcePath,
        string destinationPath
    )
    {
        AnsiConsole.WriteLine();

        using CancellationTokenSource cts = new();

        ConsoleCancelEventHandler cancelHandler = (_, e) =>
        {
            e.Cancel = true;
            cts.Cancel();
            AnsiConsole.MarkupLine($"[yellow]{Messages.Cancelling}[/]");
        };

        Console.CancelKeyPress += cancelHandler;

        try
        {
            var sw = Stopwatch.StartNew();
            List<string> errors = [];
            var processedFiles = 0;
            long totalBytes = 0;

            var sourceDir = Directory.Exists(sourcePath)
                ? sourcePath
                : Path.GetDirectoryName(sourcePath) ?? sourcePath;

            string[] files =
                File.Exists(sourcePath) && !Directory.Exists(sourcePath)
                    ? [sourcePath]
                    : [
                        .. Directory
                            .GetFiles(sourceDir, "*", SearchOption.AllDirectories)
                            .Where(file =>
                                !string.Equals(
                                    Path.GetFileName(file),
                                    BackupConstants.ManifestFileName,
                                    StringComparison.OrdinalIgnoreCase
                                )
                            ),
                    ];

            var totalFileCount = files.Length;
            Directory.CreateDirectory(destinationPath);

            await AnsiConsole
                .Progress()
                .AutoClear(false)
                .HideCompleted(false)
                .Columns(
                    new TaskDescriptionColumn(),
                    new ProgressBarColumn(),
                    new PercentageColumn(),
                    new RemainingTimeColumn(),
                    new SpinnerColumn()
                )
                .StartAsync(async ctx =>
                {
                    var task = ctx.AddTask(
                        $"[cyan]{string.Format(Messages.OperationIngFormat, Messages.Copying)}[/]",
                        maxValue: Math.Max(totalFileCount, 1)
                    );

                    foreach (var file in files)
                    {
                        cts.Token.ThrowIfCancellationRequested();

                        var relativePath = Path.GetRelativePath(sourceDir, file);
                        var destFile = Path.Combine(destinationPath, relativePath);
                        var destDir = Path.GetDirectoryName(destFile);

                        if (destDir is not null)
                        {
                            Directory.CreateDirectory(destDir);
                        }

                        try
                        {
                            await using FileStream sourceStream = new(
                                file,
                                FileMode.Open,
                                FileAccess.Read,
                                FileShare.Read,
                                4096,
                                useAsync: true
                            );
                            await using FileStream destStream = new(
                                destFile,
                                FileMode.Create,
                                FileAccess.Write,
                                FileShare.None,
                                4096,
                                useAsync: true
                            );
                            await sourceStream.CopyToAsync(destStream, cts.Token);

                            totalBytes += new FileInfo(file).Length;
                            processedFiles++;
                        }
                        catch (Exception ex) when (ex is not OperationCanceledException)
                        {
                            errors.Add($"{relativePath}: {ex.Message}");
                        }

                        task.Value = processedFiles + errors.Count;
                        task.Description =
                            $"[cyan]{string.Format(Messages.OperationIngFilesFormat, Messages.Copying, processedFiles, totalFileCount)}[/]";
                    }
                });

            sw.Stop();

            BackupResult result = new(
                errors.Count == 0,
                sw.Elapsed,
                totalBytes,
                processedFiles,
                totalFileCount,
                errors,
                []
            );

            ResultRenderer.Print(result, operationName);
        }
        catch (OperationCanceledException)
        {
            AnsiConsole.MarkupLine($"[yellow]{Messages.OperationCancelledByUser}[/]");
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.UnexpectedErrorFormat, Markup.Escape(ex.Message))}[/]"
            );
        }
        finally
        {
            Console.CancelKeyPress -= cancelHandler;
        }
    }

    private static void PrintFailure(string operationName, string[] errors) =>
        AnsiConsole.MarkupLine(
            $"[red]{string.Format(Messages.FailedFormat, operationName, Markup.Escape(string.Join(", ", errors)))}[/]"
        );

    private static void PrintSummary(
        string operationName,
        string sourcePath,
        string destinationPath,
        IEncryptionAlgorithmStrategy? encryption,
        IKeyDerivationAlgorithmStrategy? kdf,
        ICompressionStrategy? compression
    )
    {
        AnsiConsole.WriteLine();
        var summaryTable = new Table()
            .Border(TableBorder.Rounded)
            .BorderColor(Color.Grey)
            .Title($"[bold cyan]{operationName} {Messages.SummaryTitle}[/]")
            .AddColumn(new TableColumn($"[bold]{Messages.Setting}[/]").LeftAligned())
            .AddColumn(new TableColumn($"[bold]{Messages.Value}[/]").LeftAligned());

        summaryTable.AddRow(Messages.Source, Markup.Escape(sourcePath));
        summaryTable.AddRow(Messages.Destination, Markup.Escape(destinationPath));

        if (encryption is not null)
        {
            summaryTable.AddRow(Messages.EncryptionLabel, Markup.Escape(encryption.DisplayName));
        }

        if (kdf is not null)
        {
            summaryTable.AddRow(Messages.KeyDerivationLabel, Markup.Escape(kdf.DisplayName));
        }

        if (compression is not null)
        {
            summaryTable.AddRow(Messages.CompressionLabel, Markup.Escape(compression.DisplayName));
        }

        AnsiConsole.Write(summaryTable);
        AnsiConsole.WriteLine();
    }

    private static void PrintValidationErrors(IReadOnlyList<string> errors)
    {
        AnsiConsole.MarkupLine($"[red]{Messages.ValidationErrors}[/]");
        foreach (var error in errors)
        {
            AnsiConsole.MarkupLine($"  [red]❌ {Markup.Escape(error)}[/]");
        }
    }

    private static string PromptDecryptionPassword() =>
        AnsiConsole.Prompt(
            new TextPrompt<string>($"[green]{Messages.PasswordPrompt}[/]:")
                .Secret()
                .ValidationErrorMessage($"[red]{Messages.PasswordCannotBeEmpty}[/]")
                .Validate(p =>
                    !string.IsNullOrWhiteSpace(p)
                        ? ValidationResult.Success()
                        : ValidationResult.Error($"[red]{Messages.PasswordCannotBeEmpty}[/]")
                )
        );

    private (string Password, string ConfirmPassword, bool WasAutoGenerated) PromptPasswords()
    {
        while (true)
        {
            var password = AnsiConsole.Prompt(
                new TextPrompt<string>(
                    $"[green]{Messages.PasswordPrompt}[/] {Messages.PasswordPromptHint}"
                )
                    .Secret()
                    .AllowEmpty()
            );

            if (string.IsNullOrWhiteSpace(password))
            {
                const int autoGeneratedLength = 50;
                const PasswordGenerationOptions autoGeneratedOptions =
                    PasswordGenerationOptions.IncludeUppercase
                    | PasswordGenerationOptions.IncludeLowercase
                    | PasswordGenerationOptions.IncludeNumbers
                    | PasswordGenerationOptions.IncludeSpecialCharacters;

                password = passwordService.GeneratePassword(
                    autoGeneratedLength,
                    autoGeneratedOptions
                );
                return (password, password, true);
            }

            var strength = passwordService.AnalyzePasswordStrength(password);
            var strengthColor = strength.Strength switch
            {
                PasswordStrength.VeryWeak => "red",
                PasswordStrength.Weak => "red",
                PasswordStrength.Fair => "yellow",
                PasswordStrength.Good => "green",
                PasswordStrength.Strong => "bold green",
                _ => "white",
            };
            AnsiConsole.MarkupLine(
                $"  {Messages.PasswordStrengthLabel} [{strengthColor}]{Markup.Escape(strength.Description)}[/]"
            );

            var confirmPassword = AnsiConsole.Prompt(
                new TextPrompt<string>($"[green]{Messages.ConfirmPasswordPrompt}[/]:").Secret()
            );

            return (password, confirmPassword, false);
        }
    }

    private ICompressionStrategy? ResolveCompressionStrategy(BackupCreationSettings settings)
    {
        if (settings.CompressionMode == CompressionMode.None)
        {
            return null;
        }

        return compressionStrategies.FirstOrDefault(strategy =>
                strategy.Id == settings.CompressionMode
            )
            ?? throw new InvalidOperationException(
                $"No compression strategy is registered for '{settings.CompressionMode}'."
            );
    }

    private IEncryptionAlgorithmStrategy? ResolveEncryptionStrategy(BackupCreationSettings settings)
    {
        if (settings.EncryptionAlgorithm == EncryptionAlgorithm.None)
        {
            return null;
        }

        return encryptionStrategies.FirstOrDefault(strategy =>
                strategy.Id == settings.EncryptionAlgorithm
            )
            ?? throw new InvalidOperationException(
                $"No encryption strategy is registered for '{settings.EncryptionAlgorithm}'."
            );
    }

    private IKeyDerivationAlgorithmStrategy? ResolveKeyDerivationStrategy(
        BackupCreationSettings settings
    )
    {
        if (settings.EncryptionAlgorithm == EncryptionAlgorithm.None)
        {
            return null;
        }

        return keyDerivationStrategies.FirstOrDefault(strategy =>
                strategy.Id == settings.KeyDerivationAlgorithm
            )
            ?? throw new InvalidOperationException(
                $"No key derivation strategy is registered for '{settings.KeyDerivationAlgorithm}'."
            );
    }

    private static ManifestKind DetectManifestKind(string sourcePath)
    {
        var dir = Directory.Exists(sourcePath)
            ? sourcePath
            : Path.GetDirectoryName(sourcePath) ?? string.Empty;

        if (string.IsNullOrEmpty(dir))
        {
            return ManifestKind.Missing;
        }

        var manifestPath = Path.Combine(dir, BackupConstants.ManifestFileName);
        if (!File.Exists(manifestPath))
        {
            return ManifestKind.Missing;
        }

        try
        {
            using FileStream fs = new(manifestPath, FileMode.Open, FileAccess.Read, FileShare.Read);

            // The first byte distinguishes the manifest format: '{' is the plain JSON
            // manifest written by plain copies, 0 is an unencrypted chunked manifest
            // (EncryptionAlgorithm.None) and any other value an encrypted preamble.
            return fs.ReadByte() switch
            {
                < 0 => ManifestKind.Missing,
                '{' => ManifestKind.PlainCopy,
                0 => ManifestKind.UnencryptedChunked,
                _ => ManifestKind.Encrypted,
            };
        }
        catch
        {
            return ManifestKind.Missing;
        }
    }

    private async Task<BackupResult?> HandleWarningsAsync(
        BackupResult response,
        BackupRequest request,
        string operationName,
        string operationIngName,
        CancellationToken cancellationToken
    )
    {
        AnsiConsole.MarkupLine($"⚠  [yellow]{Messages.WarningsLabel}[/]");
        foreach (var warning in response.Warnings)
        {
            AnsiConsole.MarkupLine($"  - [yellow]{Markup.Escape(warning)}[/]");
        }

        AnsiConsole.WriteLine();

        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ContinueDespiteWarningsFormat, operationName.ToUpperInvariant())}[/]",
                cancellationToken: cancellationToken
            )
        )
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return null;
        }

        var proceedRequest = request with { ProceedOnWarnings = true };

        var result = await ProgressRunner.RunAsync(
            orchestrator,
            proceedRequest,
            operationIngName,
            cancellationToken
        );

        if (!result.IsSuccess)
        {
            PrintFailure(operationName, result.Errors);
            return null;
        }

        return result.Value;
    }

    private static void PrintGeneratedPassword(string password)
    {
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine($"[yellow]{Messages.AutoGeneratedPasswordNotice}[/]");
        AnsiConsole.WriteLine();

        Panel passwordPanel = new(
            new Rows(
                new Markup($"[bold]{Markup.Escape(password)}[/]"),
                new Text(string.Empty),
                new Markup(
                    $"[dim]{Messages.LengthLabel}[/]   {password.Length} {Messages.CharactersLabel}"
                )
            )
        )
        {
            Header = new PanelHeader($"{Messages.GeneratedPasswordHeader}"),
            Border = BoxBorder.Rounded,
            BorderStyle = new Style(Color.Cyan1),
            Padding = new Padding(1, 1),
        };

        AnsiConsole.Write(passwordPanel);
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine($"\u26a0  [yellow]{Messages.PasswordStorageWarning}[/]");
        AnsiConsole.WriteLine();
    }

    private async Task RunOperationAsync(
        BackupRequest request,
        string operationName,
        string operationIngName
    )
    {
        AnsiConsole.WriteLine();

        using CancellationTokenSource cts = new();

        // The handler must be removed afterwards: leaving it subscribed would make a
        // later Ctrl+C invoke it on an already disposed CancellationTokenSource.
        ConsoleCancelEventHandler cancelHandler = (_, e) =>
        {
            e.Cancel = true;
            cts.Cancel();
            AnsiConsole.MarkupLine($"[yellow]{Messages.Cancelling}[/]");
        };

        Console.CancelKeyPress += cancelHandler;

        try
        {
            var result = await ProgressRunner.RunAsync(
                orchestrator,
                request,
                operationIngName,
                cts.Token
            );

            if (!result.IsSuccess)
            {
                PrintFailure(operationName, result.Errors);
                return;
            }

            var response = result.Value;

            if (response.HasErrors && response.TotalFiles == 0 && response.ProcessedFiles == 0)
            {
                PrintValidationErrors(response.Errors);
                return;
            }

            if (response.HasWarnings && !request.ProceedOnWarnings)
            {
                response = await HandleWarningsAsync(
                    response,
                    request,
                    operationName,
                    operationIngName,
                    cts.Token
                );

                if (response is null)
                {
                    return;
                }
            }

            ResultRenderer.Print(response, operationName);
        }
        catch (OperationCanceledException)
        {
            AnsiConsole.MarkupLine($"[yellow]{Messages.OperationCancelledByUser}[/]");
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.UnexpectedErrorFormat, Markup.Escape(ex.Message))}[/]"
            );
        }
        finally
        {
            Console.CancelKeyPress -= cancelHandler;
        }
    }

    private enum ManifestKind
    {
        Missing = 0,
        PlainCopy = 1,
        UnencryptedChunked = 2,
        Encrypted = 3,
    }
}
