namespace BackupZCrypt.Terminal.Commands;

using BackupZCrypt.Application.Orchestrators.Interfaces;
using BackupZCrypt.Application.Services.Interfaces;
using BackupZCrypt.Application.ValueObjects;
using BackupZCrypt.Application.ValueObjects.Manifest;
using BackupZCrypt.Application.ValueObjects.Password;
using BackupZCrypt.Domain.Constants;
using BackupZCrypt.Domain.Enums;
using BackupZCrypt.Domain.Exceptions;
using BackupZCrypt.Domain.Strategies.Interfaces;
using BackupZCrypt.Domain.ValueObjects.FileCrypt;
using BackupZCrypt.Terminal.Rendering;
using BackupZCrypt.Terminal.Resources;
using Spectre.Console;
using System.Diagnostics;

internal sealed class BackupCommand(
    IFileCryptOrchestrator orchestrator,
    IPasswordService passwordService,
    IManifestService manifestService,
    IReadOnlyList<IEncryptionAlgorithmStrategy> encryptionStrategies,
    IReadOnlyList<IKeyDerivationAlgorithmStrategy> keyDerivationStrategies,
    IReadOnlyList<INameObfuscationStrategy> nameObfuscationStrategies,
    IReadOnlyList<ICompressionStrategy> compressionStrategies)
{
    public async Task ExecuteAsync(EncryptOperation operation)
    {
        string operationName =
            operation == EncryptOperation.Encrypt ? Messages.CreateBackup : Messages.RestoreBackup;

        AnsiConsole.Write(
            new Rule($"[bold cyan]{operationName}[/]").RuleStyle(Style.Parse("grey")));
        AnsiConsole.WriteLine();

        string sourcePath = PromptSourcePath();
        string destinationPath = PromptDestinationPath();

        if (operation == EncryptOperation.Encrypt)
        {
            await ExecuteCreateBackupAsync(operationName, sourcePath, destinationPath);
        }
        else
        {
            await ExecuteRestoreBackupAsync(operationName, sourcePath, destinationPath);
        }
    }

    private async Task ExecuteCreateBackupAsync(
        string operationName,
        string sourcePath,
        string destinationPath)
    {
        IEncryptionAlgorithmStrategy? selectedEncryption = PromptOptionalStrategy(
            Messages.EncryptionAlgorithmPrompt,
            encryptionStrategies,
            s => $"{s.DisplayName} — {s.Summary}",
            Messages.NoneNoEncryption);

        string password = string.Empty;
        string confirmPassword = string.Empty;
        IKeyDerivationAlgorithmStrategy? selectedKdf = null;
        var wasAutoGenerated = false;

        if (selectedEncryption is not null)
        {
            (password, confirmPassword, wasAutoGenerated) = PromptPasswords();

            if (wasAutoGenerated)
            {
                PrintGeneratedPassword(password);
            }

            selectedKdf = PromptStrategy(
                Messages.KeyDerivationAlgorithmPrompt,
                keyDerivationStrategies,
                s => $"{s.DisplayName} — {s.Summary}");
        }

        ICompressionStrategy? selectedCompression = PromptOptionalStrategy(
            Messages.CompressionModePrompt,
            compressionStrategies,
            s => $"{s.DisplayName} — {s.Summary}",
            Messages.NoneNoCompression);

        INameObfuscationStrategy? selectedObfuscation = null;
        if (selectedEncryption is not null)
        {
            selectedObfuscation = PromptOptionalStrategy(
                Messages.NameObfuscationModePrompt,
                nameObfuscationStrategies,
                s => $"{s.DisplayName} — {s.Summary}",
                Messages.NoneNoObfuscation);
        }

        PrintSummary(
            operationName,
            sourcePath,
            destinationPath,
            selectedEncryption,
            selectedKdf,
            selectedObfuscation,
            selectedCompression);

        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ProceedConfirmFormat, operationName.ToUpperInvariant())}[/]"))
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return;
        }

        if (selectedEncryption is not null)
        {
            FileCryptRequest request = new(
                sourcePath,
                destinationPath,
                password,
                confirmPassword,
                selectedEncryption.Id,
                selectedKdf!.Id,
                EncryptOperation.Encrypt,
                selectedObfuscation?.Id ?? NameObfuscationMode.None,
                selectedCompression?.Id ?? CompressionMode.None,
                ProceedOnWarnings: false);

            await RunOperationAsync(request, operationName, Messages.Encrypting);
        }
        else if (selectedCompression is not null)
        {
            FileCryptRequest request = new(
                sourcePath,
                destinationPath,
                string.Empty,
                string.Empty,
                default,
                default,
                EncryptOperation.Encrypt,
                NameObfuscationMode.None,
                selectedCompression.Id,
                ProceedOnWarnings: false,
                UseEncryption: false);

            await RunOperationAsync(request, operationName, Messages.Compressing);
        }
        else
        {
            await ExecutePlainCopyAsync(operationName, sourcePath, destinationPath);
        }
    }

    private async Task ExecuteRestoreBackupAsync(
        string operationName,
        string sourcePath,
        string destinationPath)
    {
        if (!DetectManifest(sourcePath))
        {
            AnsiConsole.MarkupLine($"[red]{Messages.ManifestNotFound}[/]");
            return;
        }

        bool isEncrypted = DetectEncryptedManifest(sourcePath);

        string password = string.Empty;
        if (isEncrypted)
        {
            AnsiConsole.MarkupLine($"[cyan]{Messages.EncryptedBackupDetected}[/]");
            password = PromptDecryptionPassword();
        }
        else
        {
            AnsiConsole.MarkupLine($"[dim]{Messages.NoEncryptionDetected}[/]");
        }

        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ProceedConfirmFormat, operationName.ToUpperInvariant())}[/]"))
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return;
        }

        if (isEncrypted)
        {
            FileCryptRequest request = new(
                sourcePath,
                destinationPath,
                password,
                password,
                EncryptionAlgorithm.Aes,
                KeyDerivationAlgorithm.Argon2id,
                EncryptOperation.Decrypt,
                NameObfuscationMode.None);

            await RunOperationAsync(request, operationName, Messages.Decrypting);
        }
        else
        {
            FileCryptRequest request = new(
                sourcePath,
                destinationPath,
                string.Empty,
                string.Empty,
                default,
                default,
                EncryptOperation.Decrypt,
                NameObfuscationMode.None,
                compressionStrategies[0].Id,
                ProceedOnWarnings: false,
                UseEncryption: false);

            await RunOperationAsync(request, operationName, Messages.Decompressing);
        }
    }

    private async Task ExecutePlainCopyAsync(
        string operationName,
        string sourcePath,
        string destinationPath)
    {
        if (
            !await AnsiConsole.ConfirmAsync(
                $"[yellow]{string.Format(Messages.ProceedConfirmFormat, operationName.ToUpperInvariant())}[/]"))
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return;
        }

        AnsiConsole.WriteLine();

        using CancellationTokenSource cts = new();

        Console.CancelKeyPress += (_, e) =>
        {
            e.Cancel = true;
            cts.Cancel();
            AnsiConsole.MarkupLine($"[yellow]{Messages.Cancelling}[/]");
        };

        try
        {
            Stopwatch sw = Stopwatch.StartNew();
            List<string> errors = [];
            int processedFiles = 0;
            long totalBytes = 0;
            int totalFileCount;

            if (Directory.Exists(sourcePath))
            {
                string[] files = Directory.GetFiles(
                    sourcePath, "*", SearchOption.AllDirectories);
                totalFileCount = files.Length;

                await AnsiConsole
                    .Progress()
                    .AutoClear(false)
                    .HideCompleted(false)
                    .Columns(
                        new TaskDescriptionColumn(),
                        new ProgressBarColumn(),
                        new PercentageColumn(),
                        new RemainingTimeColumn(),
                        new SpinnerColumn())
                    .StartAsync(async ctx =>
                    {
                        ProgressTask task = ctx.AddTask(
                            $"[cyan]{string.Format(Messages.OperationIngFormat, Messages.Copying)}[/]",
                            maxValue: Math.Max(totalFileCount, 1));

                        foreach (string file in files)
                        {
                            cts.Token.ThrowIfCancellationRequested();

                            string relativePath = Path.GetRelativePath(sourcePath, file);
                            string destFile = Path.Combine(destinationPath, relativePath);
                            string? destDir = Path.GetDirectoryName(destFile);

                            if (destDir is not null)
                            {
                                Directory.CreateDirectory(destDir);
                            }

                            try
                            {
                                await using FileStream sourceStream = new(
                                    file, FileMode.Open, FileAccess.Read,
                                    FileShare.Read, 4096, useAsync: true);
                                await using FileStream destStream = new(
                                    destFile, FileMode.Create, FileAccess.Write,
                                    FileShare.None, 4096, useAsync: true);
                                await sourceStream.CopyToAsync(destStream, cts.Token);

                                totalBytes += new FileInfo(file).Length;
                                processedFiles++;
                            }
                            catch (Exception ex)
                                when (ex is not OperationCanceledException)
                            {
                                errors.Add($"{relativePath}: {ex.Message}");
                            }

                            task.Value = processedFiles + errors.Count;
                            task.Description =
                                $"[cyan]{string.Format(Messages.OperationIngFilesFormat, Messages.Copying, processedFiles, totalFileCount)}[/]";
                        }
                    });
            }
            else
            {
                totalFileCount = 1;

                await AnsiConsole
                    .Progress()
                    .AutoClear(false)
                    .HideCompleted(false)
                    .Columns(
                        new TaskDescriptionColumn(),
                        new ProgressBarColumn(),
                        new PercentageColumn(),
                        new SpinnerColumn())
                    .StartAsync(async ctx =>
                    {
                        ProgressTask task = ctx.AddTask(
                            $"[cyan]{string.Format(Messages.OperationIngFormat, Messages.Copying)}[/]",
                            maxValue: 1);

                        string destFile;

                        if (Directory.Exists(destinationPath))
                        {
                            destFile = Path.Combine(
                                destinationPath, Path.GetFileName(sourcePath));
                        }
                        else
                        {
                            string? destDir = Path.GetDirectoryName(destinationPath);

                            if (destDir is not null)
                            {
                                Directory.CreateDirectory(destDir);
                            }

                            destFile = destinationPath;
                        }

                        try
                        {
                            await using FileStream sourceStream = new(
                                sourcePath, FileMode.Open, FileAccess.Read,
                                FileShare.Read, 4096, useAsync: true);
                            await using FileStream destStream = new(
                                destFile, FileMode.Create, FileAccess.Write,
                                FileShare.None, 4096, useAsync: true);
                            await sourceStream.CopyToAsync(destStream, cts.Token);

                            totalBytes = new FileInfo(sourcePath).Length;
                            processedFiles = 1;
                        }
                        catch (Exception ex)
                            when (ex is not OperationCanceledException)
                        {
                            errors.Add(ex.Message);
                        }

                        task.Value = 1;
                    });
            }

            sw.Stop();

            if (errors.Count == 0 && processedFiles > 0)
            {
                List<ManifestEntry> entries = [];
                string manifestDir;

                if (Directory.Exists(sourcePath))
                {
                    manifestDir = destinationPath;
                    string[] files = Directory.GetFiles(
                        destinationPath, "*", SearchOption.AllDirectories);

                    foreach (string file in files)
                    {
                        string relativePath = Path.GetRelativePath(destinationPath, file);
                        entries.Add(new ManifestEntry(
                            relativePath,
                            relativePath,
                            string.Empty,
                            string.Empty));
                    }
                }
                else
                {
                    string destFile = Directory.Exists(destinationPath)
                        ? Path.Combine(destinationPath, Path.GetFileName(sourcePath))
                        : destinationPath;
                    manifestDir = Path.GetDirectoryName(destFile) ?? destinationPath;
                    string fileName = Path.GetFileName(destFile);
                    entries.Add(new ManifestEntry(
                        fileName,
                        fileName,
                        string.Empty,
                        string.Empty));
                }

                ManifestHeader header = new(
                    default,
                    default,
                    NameObfuscationMode.None,
                    CompressionMode.None);

                await manifestService.TrySavePlainManifestAsync(
                    entries,
                    header,
                    manifestDir,
                    cts.Token);
            }

            FileCryptResult result = new(
                errors.Count == 0,
                sw.Elapsed,
                totalBytes,
                processedFiles,
                totalFileCount,
                errors,
                []);

            ResultRenderer.Print(result, operationName);
        }
        catch (OperationCanceledException)
        {
            AnsiConsole.MarkupLine($"[yellow]{Messages.OperationCancelledByUser}[/]");
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.UnexpectedErrorFormat, Markup.Escape(ex.Message))}[/]");
        }
    }

    private static void PrintFailure(string operationName, string[] errors) =>
        AnsiConsole.MarkupLine(
            $"[red]{string.Format(Messages.FailedFormat, operationName, Markup.Escape(string.Join(", ", errors)))}[/]");

    private static void PrintSummary(
        string operationName,
        string sourcePath,
        string destinationPath,
        IEncryptionAlgorithmStrategy? encryption,
        IKeyDerivationAlgorithmStrategy? kdf,
        INameObfuscationStrategy? obfuscation,
        ICompressionStrategy? compression)
    {
        AnsiConsole.WriteLine();
        Table summaryTable = new Table()
            .Border(TableBorder.Rounded)
            .BorderColor(Color.Grey)
            .Title($"[bold cyan]{operationName} {Messages.SummaryTitle}[/]")
            .AddColumn(new TableColumn($"[bold]{Messages.Setting}[/]").LeftAligned())
            .AddColumn(new TableColumn($"[bold]{Messages.Value}[/]").LeftAligned());

        summaryTable.AddRow(Messages.Source, Markup.Escape(sourcePath));
        summaryTable.AddRow(Messages.Destination, Markup.Escape(destinationPath));

        if (encryption is not null)
        {
            summaryTable.AddRow(Messages.EncryptionLabel, Markup.Escape(encryption.DisplayName));
        }

        if (kdf is not null)
        {
            summaryTable.AddRow(Messages.KeyDerivationLabel, Markup.Escape(kdf.DisplayName));
        }

        if (obfuscation is not null)
        {
            summaryTable.AddRow(Messages.NameObfuscationLabel, Markup.Escape(obfuscation.DisplayName));
        }

        if (compression is not null)
        {
            summaryTable.AddRow(Messages.CompressionLabel, Markup.Escape(compression.DisplayName));
        }

        AnsiConsole.Write(summaryTable);
        AnsiConsole.WriteLine();
    }

    private static void PrintValidationErrors(IReadOnlyList<string> errors)
    {
        AnsiConsole.MarkupLine($"[red]{Messages.ValidationErrors}[/]");
        foreach (string error in errors)
        {
            AnsiConsole.MarkupLine($"  [red]❌ {Markup.Escape(error)}[/]");
        }
    }

    private static string PromptDestinationPath() =>
        AnsiConsole.Prompt(
            new TextPrompt<string>($"[green]{Messages.DestinationPathPrompt}[/]:")
                .ValidationErrorMessage($"[red]{Messages.PathCannotBeEmpty}[/]")
                .Validate(p =>
                    !string.IsNullOrWhiteSpace(p)
                        ? ValidationResult.Success()
                        : ValidationResult.Error($"[red]{Messages.PleaseEnterDestinationPath}[/]")));

    private static string PromptDecryptionPassword() =>
        AnsiConsole.Prompt(
            new TextPrompt<string>($"[green]{Messages.PasswordPrompt}[/]:")
                .Secret()
                .ValidationErrorMessage($"[red]{Messages.PasswordCannotBeEmpty}[/]")
                .Validate(p =>
                    !string.IsNullOrWhiteSpace(p)
                        ? ValidationResult.Success()
                        : ValidationResult.Error($"[red]{Messages.PasswordCannotBeEmpty}[/]")));

    private (string Password, string ConfirmPassword, bool WasAutoGenerated) PromptPasswords()
    {
        while (true)
        {
            string password = AnsiConsole.Prompt(
                new TextPrompt<string>(
                    $"[green]{Messages.PasswordPrompt}[/] {Messages.PasswordPromptHint}")
                    .Secret()
                    .AllowEmpty());

            if (string.IsNullOrWhiteSpace(password))
            {
                const int autoGeneratedLength = 50;
                const PasswordGenerationOptions autoGeneratedOptions =
                    PasswordGenerationOptions.IncludeUppercase
                    | PasswordGenerationOptions.IncludeLowercase
                    | PasswordGenerationOptions.IncludeNumbers
                    | PasswordGenerationOptions.IncludeSpecialCharacters;

                password = passwordService.GeneratePassword(
                    autoGeneratedLength,
                    autoGeneratedOptions);
                return (password, password, true);
            }

            PasswordStrengthAnalysis strength = passwordService.AnalyzePasswordStrength(password);
            string strengthColor = strength.Strength switch
            {
                PasswordStrength.VeryWeak => "red",
                PasswordStrength.Weak => "red",
                PasswordStrength.Fair => "yellow",
                PasswordStrength.Good => "green",
                PasswordStrength.Strong => "bold green",
                _ => "white",
            };
            AnsiConsole.MarkupLine(
                $"  {Messages.PasswordStrengthLabel} [{strengthColor}]{Markup.Escape(strength.Description)}[/]");

            if (strength.Strength is PasswordStrength.VeryWeak or PasswordStrength.Weak
                && AnsiConsole.Confirm(
                    $"[yellow]{Messages.WeakPasswordConfirm}[/]",
                    defaultValue: true))
            {
                AnsiConsole.WriteLine();
                continue;
            }

            string confirmPassword = AnsiConsole.Prompt(
                new TextPrompt<string>($"[green]{Messages.ConfirmPasswordPrompt}[/]:").Secret());

            return (password, confirmPassword, false);
        }
    }

    private static string PromptSourcePath() =>
        AnsiConsole.Prompt(
            new TextPrompt<string>(
                $"[green]{Messages.SourcePathPrompt}[/] {Messages.SourcePathHint}")
                .ValidationErrorMessage($"[red]{Messages.PathCannotBeEmpty}[/]")
                .Validate(p =>
                    !string.IsNullOrWhiteSpace(p) && (File.Exists(p) || Directory.Exists(p))
                        ? ValidationResult.Success()
                        : ValidationResult.Error($"[red]{Messages.PathDoesNotExist}[/]")));

    private static T PromptStrategy<T>(
        string title,
        IReadOnlyList<T> strategies,
        Func<T, string> converter)
        where T : class =>
        AnsiConsole.Prompt(
            new SelectionPrompt<T>()
                .Title($"[green]{title}[/]")
                .HighlightStyle(Style.Parse("bold cyan"))
                .UseConverter(converter)
                .AddChoices(strategies));

    private static T? PromptOptionalStrategy<T>(
        string title,
        IReadOnlyList<T> strategies,
        Func<T, string> converter,
        string noneLabel)
        where T : class
    {
        List<string> displayChoices = [noneLabel, .. strategies.Select(converter)];

        string selected = AnsiConsole.Prompt(
            new SelectionPrompt<string>()
                .Title($"[green]{title}[/]")
                .HighlightStyle(Style.Parse("bold cyan"))
                .AddChoices(displayChoices));

        if (selected == noneLabel)
        {
            return null;
        }

        int index = displayChoices.IndexOf(selected) - 1;
        return strategies[index];
    }

    private static bool DetectManifest(string sourcePath)
    {
        string dir = Directory.Exists(sourcePath)
            ? sourcePath
            : Path.GetDirectoryName(sourcePath) ?? string.Empty;

        return !string.IsNullOrEmpty(dir)
            && File.Exists(Path.Combine(dir, FileCryptConstants.ManifestFileName));
    }

    private static bool DetectEncryptedManifest(string sourcePath)
    {
        string dir = Directory.Exists(sourcePath)
            ? sourcePath
            : Path.GetDirectoryName(sourcePath) ?? string.Empty;

        if (string.IsNullOrEmpty(dir))
        {
            return false;
        }

        string manifestPath = Path.Combine(dir, FileCryptConstants.ManifestFileName);
        if (!File.Exists(manifestPath))
        {
            return false;
        }

        try
        {
            using FileStream fs = new(manifestPath, FileMode.Open, FileAccess.Read, FileShare.Read);
            int firstByte = fs.ReadByte();
            return firstByte >= 0 && firstByte != '{';
        }
        catch
        {
            return false;
        }
    }

    private async Task<FileCryptResult?> HandleWarningsAsync(
        FileCryptResult response,
        FileCryptRequest request,
        string operationName,
        string operationIngName,
        CancellationToken cancellationToken)
    {
        AnsiConsole.MarkupLine($"⚠  [yellow]{Messages.WarningsLabel}[/]");
        foreach (string warning in response.Warnings)
        {
            AnsiConsole.MarkupLine($"  - [yellow]{Markup.Escape(warning)}[/]");
        }

        AnsiConsole.WriteLine();

        if (
            !await AnsiConsole.ConfirmAsync($"[yellow]{string.Format(Messages.ContinueDespiteWarningsFormat, operationName.ToUpperInvariant())}[/]", cancellationToken: cancellationToken))
        {
            AnsiConsole.MarkupLine($"[grey]{Messages.OperationCancelled}[/]");
            return null;
        }

        FileCryptRequest proceedRequest = request with { ProceedOnWarnings = true };

        Result<FileCryptResult> result = await ProgressRunner.RunAsync(
            orchestrator,
            proceedRequest,
            operationIngName,
            cancellationToken);

        if (!result.IsSuccess)
        {
            PrintFailure(operationName, result.Errors);
            return null;
        }

        return result.Value;
    }

    private static void PrintGeneratedPassword(string password)
    {
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine($"[yellow]{Messages.AutoGeneratedPasswordNotice}[/]");
        AnsiConsole.WriteLine();

        Panel passwordPanel = new(
            new Rows(
                new Markup($"[bold]{Markup.Escape(password)}[/]"),
                new Text(string.Empty),
                new Markup(
                    $"[dim]{Messages.LengthLabel}[/]   {password.Length} {Messages.CharactersLabel}")))
        {
            Header = new PanelHeader($"{Messages.GeneratedPasswordHeader}"),
            Border = BoxBorder.Rounded,
            BorderStyle = new Style(Color.Cyan1),
            Padding = new Padding(1, 1),
        };

        AnsiConsole.Write(passwordPanel);
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine($"\u26a0  [yellow]{Messages.PasswordStorageWarning}[/]");
        AnsiConsole.WriteLine();
    }

    private async Task RunOperationAsync(
        FileCryptRequest request,
        string operationName,
        string operationIngName)
    {
        AnsiConsole.WriteLine();

        using CancellationTokenSource cts = new();

        Console.CancelKeyPress += (_, e) =>
        {
            e.Cancel = true;
            cts.Cancel();
            AnsiConsole.MarkupLine($"[yellow]{Messages.Cancelling}[/]");
        };

        try
        {
            Result<FileCryptResult> result = await ProgressRunner.RunAsync(
                orchestrator,
                request,
                operationIngName,
                cts.Token);

            if (!result.IsSuccess)
            {
                PrintFailure(operationName, result.Errors);
                return;
            }

            FileCryptResult? response = result.Value;

            if (response.HasErrors && response.TotalFiles == 0 && response.ProcessedFiles == 0)
            {
                PrintValidationErrors(response.Errors);
                return;
            }

            if (response.HasWarnings && !request.ProceedOnWarnings)
            {
                response = await HandleWarningsAsync(
                    response,
                    request,
                    operationName,
                    operationIngName,
                    cts.Token);

                if (response is null)
                {
                    return;
                }
            }

            ResultRenderer.Print(response, operationName);
        }
        catch (OperationCanceledException)
        {
            AnsiConsole.MarkupLine($"[yellow]{Messages.OperationCancelledByUser}[/]");
        }
        catch (EncryptionException ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]❌ {Markup.Escape(ex.Code.ToString())}: {Markup.Escape(ex.Message)}[/]");
        }
        catch (ValidationException ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.ValidationErrorFormat, Markup.Escape(ex.Message))}[/]");
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine(
                $"[red]{string.Format(Messages.UnexpectedErrorFormat, Markup.Escape(ex.Message))}[/]");
        }
    }
}
