<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AnalysisMode>Default</AnalysisMode>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="Roslynator.Analyzers" />
    <PackageReference Remove="Roslynator.Formatting.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackupZCrypt.Domain\BackupZCrypt.Domain.csproj" />
    <ProjectReference Include="..\BackupZCrypt.Application\BackupZCrypt.Application.csproj" />
    <ProjectReference Include="..\BackupZCrypt.Infrastructure\BackupZCrypt.Infrastructure.csproj" />
    <ProjectReference Include="..\BackupZCrypt.Composition\BackupZCrypt.Composition.csproj" />
    <ProjectReference Include="..\BackupZCrypt.Desktop\BackupZCrypt.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\BackupZCrypt.Desktop\Resources\Strings.resx" Link="TestData\Strings.resx" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\BackupZCrypt.Desktop\Resources\Strings.es.resx" Link="TestData\Strings.es.resx" CopyToOutputDirectory="PreserveNewest" />
    <None Include="TestData\OnDiskFormatArchives\**\*" LinkBase="TestData\OnDiskFormatArchives" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
