//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupZCrypt.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupZCrypt.Infrastructure.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The industry standard encryption used by governments, banks, and most secure applications worldwide. Very fast on modern computers and phones thanks to built-in hardware support. Recommended for most users..
        /// </summary>
        internal static string AesDescription {
            get {
                return ResourceManager.GetString("AesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AES-256 GCM.
        /// </summary>
        internal static string AesDisplayName {
            get {
                return ResourceManager.GetString("AesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recommended — fast and widely trusted (default).
        /// </summary>
        internal static string AesSummary {
            get {
                return ResourceManager.GetString("AesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The most modern and secure way to convert your password into an encryption key. Specifically designed to resist attacks using specialized hardware (GPUs, custom chips) by requiring large amounts of memory. Recommended for most users..
        /// </summary>
        internal static string Argon2idDescription {
            get {
                return ResourceManager.GetString("Argon2idDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argon2id.
        /// </summary>
        internal static string Argon2idDisplayName {
            get {
                return ResourceManager.GetString("Argon2idDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deriving key with Argon2id.
        /// </summary>
        internal static string Argon2idKeyDerivationError {
            get {
                return ResourceManager.GetString("Argon2idKeyDerivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recommended — strongest password protection (default).
        /// </summary>
        internal static string Argon2idSummary {
            get {
                return ResourceManager.GetString("Argon2idSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A strong alternative to AES developed in Japan, with comparable security and performance. Recognized by international standards bodies and a good choice when a non-U.S. algorithm is preferred..
        /// </summary>
        internal static string CamelliaDescription {
            get {
                return ResourceManager.GetString("CamelliaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camellia-256 GCM.
        /// </summary>
        internal static string CamelliaDisplayName {
            get {
                return ResourceManager.GetString("CamelliaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strong AES alternative (international standard).
        /// </summary>
        internal static string CamelliaSummary {
            get {
                return ResourceManager.GetString("CamelliaSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A modern, fast encryption method that excels on older or low-power devices that lack dedicated AES hardware. Widely used in VPNs (WireGuard), web browsing (TLS), and messaging apps..
        /// </summary>
        internal static string ChaCha20Description {
            get {
                return ResourceManager.GetString("ChaCha20Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ChaCha20-Poly1305.
        /// </summary>
        internal static string ChaCha20DisplayName {
            get {
                return ResourceManager.GetString("ChaCha20DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fast on all devices, even without AES hardware.
        /// </summary>
        internal static string ChaCha20Summary {
            get {
                return ResourceManager.GetString("ChaCha20Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replaces the filename with a completely random unique identifier. Each file gets a different name every time, making it impossible to guess or correlate filenames..
        /// </summary>
        internal static string GuidDescription {
            get {
                return ResourceManager.GetString("GuidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUID.
        /// </summary>
        internal static string GuidDisplayName {
            get {
                return ResourceManager.GetString("GuidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fully random name (maximum privacy).
        /// </summary>
        internal static string GuidSummary {
            get {
                return ResourceManager.GetString("GuidSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No compression is applied — files are encrypted at their original size. Best when speed matters most or files are already compressed (e.g., ZIP, JPEG, MP4)..
        /// </summary>
        internal static string NoCompressionDescription {
            get {
                return ResourceManager.GetString("NoCompressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        internal static string NoCompressionDisplayName {
            get {
                return ResourceManager.GetString("NoCompressionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No compression, fastest (default).
        /// </summary>
        internal static string NoCompressionSummary {
            get {
                return ResourceManager.GetString("NoCompressionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keeps the original filename as-is. Use when you don&apos;t need to hide filenames and prefer to keep them readable and organized..
        /// </summary>
        internal static string NoObfuscationDescription {
            get {
                return ResourceManager.GetString("NoObfuscationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        internal static string NoObfuscationDisplayName {
            get {
                return ResourceManager.GetString("NoObfuscationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keeps original filename (default).
        /// </summary>
        internal static string NoObfuscationSummary {
            get {
                return ResourceManager.GetString("NoObfuscationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a decryption.
        /// </summary>
        internal static string OperationDecryption {
            get {
                return ResourceManager.GetString("OperationDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encryption.
        /// </summary>
        internal static string OperationEncryption {
            get {
                return ResourceManager.GetString("OperationEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A traditional and widely compatible method to convert your password into an encryption key. Supported everywhere, but offers less protection against attackers with specialized hardware (GPUs). Choose this when compatibility with older systems is important..
        /// </summary>
        internal static string Pbkdf2Description {
            get {
                return ResourceManager.GetString("Pbkdf2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PBKDF2 (HMAC-SHA256).
        /// </summary>
        internal static string Pbkdf2DisplayName {
            get {
                return ResourceManager.GetString("Pbkdf2DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deriving key with PBKDF2.
        /// </summary>
        internal static string Pbkdf2KeyDerivationError {
            get {
                return ResourceManager.GetString("Pbkdf2KeyDerivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum compatibility with older systems.
        /// </summary>
        internal static string Pbkdf2Summary {
            get {
                return ResourceManager.GetString("Pbkdf2Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A strong method to convert your password into an encryption key that also resists hardware-based attacks by requiring significant memory. A good middle ground between PBKDF2 and Argon2id, with wider software support than Argon2id..
        /// </summary>
        internal static string ScryptDescription {
            get {
                return ResourceManager.GetString("ScryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrypt.
        /// </summary>
        internal static string ScryptDisplayName {
            get {
                return ResourceManager.GetString("ScryptDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deriving key with scrypt.
        /// </summary>
        internal static string ScryptKeyDerivationError {
            get {
                return ResourceManager.GetString("ScryptKeyDerivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strong protection, broader compatibility than Argon2id.
        /// </summary>
        internal static string ScryptSummary {
            get {
                return ResourceManager.GetString("ScryptSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Designed with an extra-large security margin, making it one of the most conservative choices available. Noticeably slower than AES, but favored when maximum caution is the priority over speed..
        /// </summary>
        internal static string SerpentDescription {
            get {
                return ResourceManager.GetString("SerpentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serpent-256 GCM.
        /// </summary>
        internal static string SerpentDisplayName {
            get {
                return ResourceManager.GetString("SerpentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum security margin (slower than AES).
        /// </summary>
        internal static string SerpentSummary {
            get {
                return ResourceManager.GetString("SerpentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replaces the filename with a unique 64-character code based on the file content. Files with the same content always get the same name, which helps detect duplicates while hiding the original name..
        /// </summary>
        internal static string Sha256Description {
            get {
                return ResourceManager.GetString("Sha256Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHA-256.
        /// </summary>
        internal static string Sha256DisplayName {
            get {
                return ResourceManager.GetString("Sha256DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content-based name (64 characters).
        /// </summary>
        internal static string Sha256Summary {
            get {
                return ResourceManager.GetString("Sha256Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Same as SHA-256 but generates a longer 50-character code, offering even stronger uniqueness guarantees. Use when you need maximum assurance that no two different files share a name..
        /// </summary>
        internal static string Sha512Description {
            get {
                return ResourceManager.GetString("Sha512Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SHA-512.
        /// </summary>
        internal static string Sha512DisplayName {
            get {
                return ResourceManager.GetString("Sha512DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content-based name (50 characters, stronger).
        /// </summary>
        internal static string Sha512Summary {
            get {
                return ResourceManager.GetString("Sha512Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A well-respected encryption algorithm that uses a fundamentally different internal design than AES. A solid option if you want to avoid relying on a single algorithm family..
        /// </summary>
        internal static string TwofishDescription {
            get {
                return ResourceManager.GetString("TwofishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twofish-256 GCM.
        /// </summary>
        internal static string TwofishDisplayName {
            get {
                return ResourceManager.GetString("TwofishDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good alternative with a different design approach.
        /// </summary>
        internal static string TwofishSummary {
            get {
                return ResourceManager.GetString("TwofishSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zstandard compression at maximum level, achieving the smallest file sizes at the cost of longer compression time. Best for large files where minimizing size matters most..
        /// </summary>
        internal static string ZstdBestDescription {
            get {
                return ResourceManager.GetString("ZstdBestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zstandard (Best).
        /// </summary>
        internal static string ZstdBestDisplayName {
            get {
                return ResourceManager.GetString("ZstdBestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Smallest files, slowest compression.
        /// </summary>
        internal static string ZstdBestSummary {
            get {
                return ResourceManager.GetString("ZstdBestSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zstandard compression at the default level, offering a good balance between speed and compression ratio. Recommended for most use cases..
        /// </summary>
        internal static string ZstdDescription {
            get {
                return ResourceManager.GetString("ZstdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zstandard (Normal).
        /// </summary>
        internal static string ZstdDisplayName {
            get {
                return ResourceManager.GetString("ZstdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zstandard compression at minimum level, prioritizing speed over file size. Ideal when you want some compression with minimal performance impact..
        /// </summary>
        internal static string ZstdFastDescription {
            get {
                return ResourceManager.GetString("ZstdFastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zstandard (Fast).
        /// </summary>
        internal static string ZstdFastDisplayName {
            get {
                return ResourceManager.GetString("ZstdFastDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fastest compression, larger files.
        /// </summary>
        internal static string ZstdFastSummary {
            get {
                return ResourceManager.GetString("ZstdFastSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good balance of speed and compression (recommended).
        /// </summary>
        internal static string ZstdSummary {
            get {
                return ResourceManager.GetString("ZstdSummary", resourceCulture);
            }
        }
    }
}
